config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :friends
  get 'home/about'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :model
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_model!, execpt: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_model.friend.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends
  # POST /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_model.friend.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_model.friend.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not Authorized To Edit This Friend' if @friend.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :model_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field class="form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:'First Name' %>
  </div><br/>

  <div class="field  class="form-group"">
    <%= form.text_field :last_name, class:"form-control", placeholder:'Last Name' %>
  </div><br/>

  <div class="field  class="form-group"">
    <%= form.text_field :email, class:"form-control", placeholder:'Email' %>
  </div><br/>

  <div class="field  class="form-group"">
    <%= form.text_field :phone, class:"form-control", placeholder:'Phone Number' %>
  </div><br/>

  <div class="field  class="form-group"">
    <%= form.text_field :twitter, class:"form-control", placeholder:'Twitter Handle' %>
  </div><br/>
  
  <div class="field  class="form-group"">
    <%= form.number_field :model_id, id: :friend_model_id, class:"form-control", value: current_model.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %><br/>

<%= link_to 'Show', @friend, class:'btn btn-primary' %>
<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
<%= link_to 'Back', friends_path, class:'btn btn-primary' %>

app/views/friends/index.html.erb
<% if model_signed_in? %>
<div class="card table-responsive">

<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
    </tr>
  </thead>

  <tbody class="table-striped">
    <% @friends.each do |friend| %>
      <% if friend.model == current_model %>
      <tr>
        <td><%=  link_to friend.first_name + ' ' + friend.last_name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
</div>
<br/>
<%= link_to 'New Friend', new_friend_path, class:'btn btn-secondary' %>

  <% else %>
<h1>Welcome To The Friend List App </h1>
<p> Please Log In if you already have an account Or Sign up if you don't <p/>
<% end %>

app/views/friends/new.html.erb
<h1>Add New Friends</h1>

<%= render 'form', friend: @friend %><br/>

<%= link_to 'Back', friends_path, class:'btn btn-primary' %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
  <%= @friend.first_name %>
  <%= @friend.last_name %>
  </h1>
  <p class="lead">
  <%= @friend.email %> |
  Tel:
  <%= @friend.phone %> |
  Twitter:
  <%= @friend.twitter %>
  </p>
  <hr class="my-4">
  <%= link_to 'Edit', edit_friend_path(@friend), class:'btn btn-primary' %> 
  <%= link_to 'Back', friends_path, class:'btn btn-primary' %> 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
          <% if model_signed_in? %>
          <%= link_to "Sign Out", destroy_model_session_path, method: :delete, class:"nav-link" %>
          <%= link_to "Add Friends", new_friend_path, class:"nav-link" %>
          <%= link_to "Edit Profile", edit_model_registration_path, class:"nav-link" %>
          <% else %>
          <%= link_to "Sign Up",  new_model_registration_path, class:"nav-link" %>
          <%= link_to "Sign In", new_model_session_path, class:"nav-link" %>
          <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Welcome To The Friend List App </h1>
<p> Please Log In if you already have an account Or Sign up if you don't <p/>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>FriendList App</title>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
  </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>